Lesson1 =input("NUmmber Lesson Ryazi=")
Lesson2 =input("Nummber Lesson Farsi=")
Lesson3 =input("Nummber Lesson Uloom=")
Lesson4 =input("Nummber Lesson FIsik=")
Lesson5 =input("Nummber Lesson shimmi=")
Lesson1=float(Lesson1)
Lesson2=float(Lesson2)
Lesson3=float(Lesson3)
Lesson4=float(Lesson4)
Lesson5=float(Lesson5)
print(f"Medium of Lesson= {(Lesson1+Lesson2+Lesson3+Lesson4+Lesson5)/5}")
